baseURL = '40fy.dotkg.in/'
languageCode = 'en-us'
theme = "gamex"
themesDir = "./themes/"

enableEmoji = true
paginate = 3

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
