baseURL = '40fy.dotkg.in/'
enableEmoji = true
languageCode = 'en-us'
paginate = 3
theme = "gamex"
themesDir = "./themes/"
title = "40FY Gaming"

[taxonomies]
# author = "authors"
category = "categories"
player = "players"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
