[[main]]
name = 'CLAN'
pageRef = '/clan'
weight = 10

[[main]]
name = "MATCH WITH US"
pageRef = '/play'
pre = '<i class="fab fa-discord"></i>'
weight = 40

[[main]]
name = 'BLOGS'
pageRef = '/posts'
weight = 50

[[main]]
name = 'PLAYERS'
pageRef = '/authors'
weight = 30

[[main]]
name = 'HOME'
pageRef = '/'
weight = 1

[[main]]
name = 'GOODIES'
pageRef = ''
weight = 90

[[main]]
name = 'FREE THEME'
pageRef = 'https://github.com/mrdotkg/40fyweb'
parent = 'GOODIES'
target = '_blank'
weight = 1

[[main]]
name = 'DEV COMMUNITY'
pageRef = 'https://butterops.dotkg.in'
parent = 'GOODIES'
target = '_blank'
weight = 2
