[[main]]
name = 'CLAN'
pageRef = '/about'
weight = 10

[[main]]
class = "btn_1"
name = "MATCH & PLAY"
pageRef = '/play'
weight = 80

[[main]]
name = 'BLOGS'
pageRef = '/posts'
weight = 50

[[main]]
name = 'PLAYERS'
pageRef = '/authors'
weight = 30

[[main]]
name = 'HOME'
pageRef = '/'
weight = 1

[[main]]
name = 'Free Goodies'
pageRef = ''
weight = 90

[[main]]
name = 'Free Website Theme'
pageRef = 'https://github.com/mrdotkg/40fyweb'
parent = 'Free Goodies'
target = '_blank'
weight = 1

[[main]]
name = 'Game Dev Community'
pageRef = 'https://butterops.dotkg.in'
parent = 'Free Goodies'
target = '_blank'
weight = 2
