[[main]]
name = 'Clan'
pageRef = '/about'
weight = 10

[[main]]
class = "btn_1"
name = "Match & Play"
pageRef = '/play'
weight = 1

[[main]]
name = 'Blogs'
pageRef = '/posts'
weight = 50

[[main]]
name = 'Players'
pageRef = '/authors'
weight = 30

# [[main]]
# name = 'Collection'
# pageRef = '/collections'
# weight = 40

[[main]]
name = 'Free Goodies'
pageRef = ''
weight = 90

[[main]]
name = 'Free Website Theme'
pageRef = 'https://github.com/mrdotkg/40fyweb'
parent = 'Free Goodies'
target = '_blank'
weight = 1

[[main]]
name = 'Game Dev Community'
pageRef = 'https://butterops.dotkg.in'
parent = 'Free Goodies'
target = '_blank'
weight = 2
