services:
    hugo:
        command: server --buildDrafts --buildFuture --bind 0.0.0.0
        container_name: 40fyweb
        image: jakejarvis/hugo-extended:latest
        ports:
            - 1313:1313
        volumes:
            - ./:/src

# docker run 
#     -v $(pwd):/src 
#     -p 1313:1313
#     jakejarvis/hugo-extended:latest 
#     server --buildDrafts --buildFuture --bind 0.0.0.0
