baseURL = 'https://example.org/'
languageCode = 'en-US'
paginate = 3
title = 'My New Gaming Site'
# [[menus.main]]
# name = 'Home'
# pageRef = '/'
# weight = 10
[outputs]
home = ['html', 'rss']
page = ['html']

[[menus.main]]
name = 'The Clan'
pageRef = '/'
weight = 20

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30

[[menus.main]]
name = 'Goodies'
pageRef = ''
weight = 90

[[menus.main]]
name = 'Free Website Theme'
pageRef = 'https://github.com/mrdotkg/40fyweb'
parent = 'Goodies'
target = '_blank'
weight = 1

[[menus.main]]
name = 'Game Dev Community'
pageRef = 'https://butterops.dotkg.in'
parent = 'Goodies'
target = '_blank'
weight = 2

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[pagination]
disableAliases = true
pagerSize = 3
path = 'posts'
