baseURL = 'https://example.org/'
enableEmoji = true
languageCode = 'en-US'
paginate = 3
title = 'My New Gaming Site'

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Clan'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Blogs'
pageRef = '/posts'
weight = 30

[[menus.main]]
name = 'Collections'
pageRef = '/collections'
weight = 40

[[menus.main]]
name = 'Free Goodies'
pageRef = ''
weight = 90

[[menus.main]]
name = 'Free Website Theme'
pageRef = 'https://github.com/mrdotkg/40fyweb'
parent = 'Free Goodies'
target = '_blank'
weight = 1

[[menus.main]]
name = 'Game Dev Community'
pageRef = 'https://butterops.dotkg.in'
parent = 'Free Goodies'
target = '_blank'
weight = 2

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[markup.goldmark.renderer]
unsafe = true
