# Simple workflow for deploying static content to GitHub Pages
name: Push Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write
        steps:
          - uses: actions/checkout@v3
    
          # - name: Cache Hugo resources
          #   uses: actions/cache@v3
          #   env:
          #       cache-name: cache-hugo-resources
          #   with:
          #       path: resources
          #       key: ${{ env.cache-name }}
    
          - uses: actions/setup-go@v4
            with:
                go-version: "^1.17.0"
          - run: go version
    
          - name: Setup Hugo
            uses: peaceiris/actions-hugo@v2
            with:
                hugo-version: "latest"
                extended: true
    
          - name: Build
            run: hugo
            
          - name: Deploy to GitHub Pages
            uses: JamesIves/github-pages-deploy-action@v4.5.0
            with:
              clean-exclude: pr-preview/
              force: false
              branch: gh-pages
              folder: public
              commit-message: update pages
              clean: true